# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db0b75aa532ca0fcd51ec4ac3d51a7820b87d6fdf1dd98d0e81eb74541b938b481c5952ee90088202bea97894c90c4a26f28aba0da73be94c6df803e62bf4611

test:
  secret_key_base: 486b75d242ce120d0fa336d8a6ea8036a8bb9a5eb871fb00032515508a867c69cfccebd0547364257f980ee0b3943a1c0999532c421cbfdd1d949a79df369228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
